# Generated by Django 3.0.4 on 2020-04-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blathering_app', '0002_auto_20200403_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='dangerous',
        ),
    ]
