# Generated by Django 3.0.4 on 2020-04-01 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blathering_app', '0002_auto_20200401_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('spawn_month_north', models.CharField(max_length=255)),
                ('spawn_month_south', models.CharField(max_length=255)),
                ('spawn_time', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('movement', models.CharField(max_length=255)),
                ('dangerous', models.CharField(max_length=255)),
                ('sell_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('photo_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spawn_month_north', models.CharField(max_length=255)),
                ('spawn_month_south', models.CharField(max_length=255)),
                ('spawn_time', models.CharField(max_length=255)),
                ('habitat', models.CharField(max_length=255)),
                ('shadow_size', models.CharField(max_length=255)),
                ('sell_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('photo_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('era', models.CharField(max_length=255)),
                ('head_piece', models.CharField(max_length=255)),
                ('head_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('mid_piece', models.CharField(max_length=255)),
                ('mid_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('tail_piece', models.CharField(max_length=255)),
                ('tail_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('photo_url', models.CharField(max_length=400)),
            ],
        ),
    ]
