# Generated by Django 3.0.4 on 2020-04-06 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blathering_app', '0003_remove_bug_dangerous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fossil',
            old_name='head_piece',
            new_name='piece_one',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='head_price',
            new_name='piece_one_price',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='tail_piece',
            new_name='piece_three',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='tail_price',
            new_name='piece_three_price',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='mid_piece',
            new_name='piece_two',
        ),
        migrations.RenameField(
            model_name='fossil',
            old_name='mid_price',
            new_name='piece_two_price',
        ),
        migrations.AddField(
            model_name='fossil',
            name='piece_five',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='piece_five_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='fossil',
            name='piece_four',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='piece_four_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
