# Generated by Django 3.0.4 on 2020-04-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blathering_app', '0003_bug_fish_fossil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='habitat',
            new_name='location',
        ),
    ]
